#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

if (git diff --cached --name-only | grep -i "web.config") then echo "can NOT commit web.config"; exit 1; fi
if (git diff --cached --name-only | grep -i "config.xsl") then echo "can NOT commit config.xsl"; exit 1; fi